import { NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase'
import { sendInviteEmail } from '@/lib/email'

export async function POST(req: Request) {
  const { event_id, name, email } = await req.json()
  if (!event_id || !name || !email) {
    return NextResponse.json({ error: 'Missing fields' }, { status: 400 })
  }

  // Get event
  const { data: ev } = await supabaseAdmin.from('ww_events').select('*').eq('id', event_id).single()
  if (!ev) return NextResponse.json({ error: 'Event not found' }, { status: 404 })

  // Create attendee (token auto-generated by DB)
  const { data: attendee, error } = await supabaseAdmin
    .from('ww_attendees')
    .insert({ event_id, name, email, is_organiser: false })
    .select()
    .single()

  if (error || !attendee) return NextResponse.json({ error: error?.message }, { status: 500 })

  // Send invite email (non-blocking — don't fail if email fails)
  sendInviteEmail({
    toName: name,
    toEmail: email,
    eventTitle: ev.title,
    organiserName: ev.organiser_name,
    token: attendee.token,
    eventId: event_id,
  }).catch(console.error)

  return NextResponse.json({ ...attendee, availability: {} }, { status: 201 })
}
